#!/usr/bin/env python

import os
import glob
import sys
import socket
import hashlib

sys.path.append('gen-py')
sys.path.insert(0, glob.glob('/home/cs557-inst/thrift-0.13.0/lib/py/build/lib*')[0])

from chord import FileStore
import hashlib
import socket
from chord.ttypes import SystemException, RFileMetadata, RFile, NodeID

from thrift.transport import TSocket
from thrift import Thrift
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer



def main():
    transport = TSocket.TSocket("remote06.cs.binghamton.edu", "9081")
    transport = TTransport.TBufferedTransport(transport)
    protocol = TBinaryProtocol.TBinaryProtocol(transport)
    client = FileStore.Client(protocol)

    transport.open()

## writeFile

    rfile = RFile()
    rfileMetadata = RFileMetadata('hello.txt',0) # NOTE: structure needs to be initialised with default values. otherwise, nonetype error.

    rfileMetadata.filename = "abc.txt"
    rfile.meta = rfileMetadata
    rfile.content = "New Content"

    try:
        client.writeFile(rfile);
        print("Calling writeFile()..")
        
    except SystemException as e:
        print(e)

    transport.close()

if __name__ == '__main__':

    try:
        main()
    except Thrift.TException as tx:
        print('%s' % tx.message)
